name: "pycon25_duckdb_demo"
version: "1.0.0"
config-version: 2

profile: pycon25_duckdb

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  pycon25_duckdb_demo:
    +materialized: view
    +pre-hook:
      - "{{ log_processed_data(this,full_refresh=flags.FULL_REFRESH) }}"
    staging:
      +materialized: view
    metrics:
      +materialized: incremental
      +on_schema_change: append_new_columns

vars:
  from_date: '{{ (modules.datetime.datetime.now() - modules.datetime.timedelta(days=14)).strftime("%Y-%m-%d")}}'
  to_date: '{{modules.datetime.date.today().strftime("%Y-%m-%d")}}'
