name: "pycon25_spark_demo"
version: "1.0.0"
config-version: 2

profile: pycon25_spark

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  pycon25_spark_demo:
    +materialized: view
    +post-hook:
      - "{{ log_processed_data(this) }}"
    staging:
      +materialized: view
    metrics:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +post-hook:
        - "{{ log_processed_data(this) }}"

vars:
  reprocess_window_days: 14
