name: "pycon25_spark_demo"
version: "1.0.0"
config-version: 2

profile: pycon25_spark

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  pycon25_spark_demo:
    +materialized: view
    staging:
      +materialized: view
    metrics:
      +materialized: incremental
      +on_schema_change: append_new_columns

seeds:
  +schema: raw
  +quote_columns: false

vars:
  reprocess_window_days: 14
