pycon25_spark:
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift
      port: 10000
      schema: analytics
      threads: 4
      connect_retries: 5
      connect_timeout: 60
  target: dev
