version: 2

models:
  - name: stg_trips_v1
    description: Staging model for NYC Yellow Taxi trips from parquet files (view - always fresh)
    columns:
      - name: trip_id
        tests: [not_null, unique]
      - name: trip_ts
        tests: [not_null]
      - name: trip_date
        tests: [not_null]
      - name: vendor_id
        tests: [not_null]
      - name: total_amount
        tests: [not_null]
      - name: fare_amount
      - name: tip_amount
      - name: tolls_amount
      - name: passenger_count
      - name: trip_distance

  - name: stg_trips_v2
    description: Incremental staging model for NYC Yellow Taxi trips (v2 - incremental events)
    columns:
      - name: trip_id
        tests: [not_null, unique]
      - name: trip_ts
        tests: [not_null]
      - name: trip_date
        tests: [not_null]
      - name: vendor_id
        tests: [not_null]
      - name: total_amount
        tests: [not_null]
      - name: fare_amount
      - name: tip_amount
      - name: tolls_amount
      - name: passenger_count
      - name: trip_distance

  - name: agg_daily_revenue_v1
    description: Version 1 - Full batch daily revenue aggregation (table refresh)
    columns:
      - name: trip_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_trips
        tests: [not_null]
      - name: daily_passengers
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_v2
    description: Version 2 - Incremental event processing (incremental staging, full aggregation)
    columns:
      - name: trip_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_trips
        tests: [not_null]
      - name: daily_passengers
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_v3
    description: Version 3 - Incremental aggregation with partition overwrite (recommended)
    columns:
      - name: trip_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_trips
        tests: [not_null]
      - name: daily_passengers
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_with_holidays_pandas
    description: |
      Python model demonstrating Pandas UDFs with DuckDB.
      Enriches daily revenue aggregation with US holiday information using pandas .apply() for row-level transformations.
      Best for smaller datasets or when simplicity is preferred.
    columns:
      - name: trip_date
        tests: [not_null]
      - name: is_holiday
        description: Boolean flag indicating if the date is a US holiday
      - name: holiday_name
        description: Name of the holiday if the date is a US holiday, null otherwise
      - name: daily_revenue
        tests: [not_null]
      - name: daily_trips
        tests: [not_null]
      - name: daily_passengers
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_with_holidays_pyarrow
    description: |
      Python model demonstrating PyArrow UDFs with DuckDB.
      Enriches daily revenue aggregation with US holiday information using PyArrow RecordBatchReader for batch processing.
      Memory-efficient for large datasets, processes data in chunks (batches of 100k rows).
    columns:
      - name: trip_date
        tests: [not_null]
      - name: is_holiday
        description: Boolean flag indicating if the date is a US holiday
      - name: holiday_name
        description: Name of the holiday if the date is a US holiday, null otherwise
      - name: daily_revenue
        tests: [not_null]
      - name: daily_trips
        tests: [not_null]
      - name: daily_passengers
      - name: running_revenue
        tests: [not_null]
