version: 2

models:
  - name: stg_orders_v1
    description: Staging model for Store Transactions from parquet files (view - always fresh)
    columns:
      - name: order_id
        tests: [not_null]
      - name: buyer_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]
      - name: order_timestamp
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: unit_price
        tests: [not_null]
      - name: revenue
        tests: [not_null]
      - name: payment_method
        tests: [not_null]

  - name: stg_orders_v2
    description: Incremental staging model for Store Transactions (v2 - incremental events)
    columns:
      - name: order_id
        tests: [not_null]
      - name: buyer_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]
      - name: order_timestamp
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: unit_price
        tests: [not_null]
      - name: revenue
        tests: [not_null]
      - name: payment_method
        tests: [not_null]

  - name: agg_daily_revenue_v1
    description: Version 1 - Full batch daily revenue aggregation (table refresh)
    columns:
      - name: order_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_orders
        tests: [not_null]
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_v2
    description: Version 2 - Incremental event processing (incremental staging, full aggregation)
    columns:
      - name: order_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_orders
        tests: [not_null]
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_v3
    description: Version 3 - Incremental aggregation with sliding window (recommended)
    columns:
      - name: order_date
        tests: [not_null]
      - name: daily_revenue
        tests: [not_null]
      - name: daily_orders
        tests: [not_null]
      - name: daily_buyers
        tests: [not_null]
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_with_holidays_pandas
    description: |
      Python model demonstrating Pandas UDFs with DuckDB.
      Enriches daily revenue aggregation with US holiday information using pandas .apply() for row-level transformations.
      Best for smaller datasets or when simplicity is preferred.
    columns:
      - name: order_date
        tests: [not_null]
      - name: is_holiday
        description: Boolean flag indicating if the date is a US holiday
      - name: holiday_name
        description: Name of the holiday if the date is a US holiday, null otherwise
      - name: daily_revenue
        tests: [not_null]
      - name: daily_orders
        tests: [not_null]
      - name: running_revenue
        tests: [not_null]

  - name: agg_daily_revenue_with_holidays_pyarrow
    description: |
      Python model demonstrating PyArrow UDFs with DuckDB.
      Enriches daily revenue aggregation with US holiday information using PyArrow RecordBatchReader for batch processing.
      Memory-efficient for large datasets, processes data in chunks (batches of 100k rows).
    columns:
      - name: order_date
        tests: [not_null]
      - name: is_holiday
        description: Boolean flag indicating if the date is a US holiday
      - name: holiday_name
        description: Name of the holiday if the date is a US holiday, null otherwise
      - name: daily_revenue
        tests: [not_null]
      - name: daily_orders
        tests: [not_null]
      - name: running_revenue
        tests: [not_null]
