version: 2

sources:
  - name: raw
    description: Raw NYC Taxi Trip Data in Parquet format
    schema: raw
    tables:
      - name: yellow_trips
        description: Yellow Taxi trip records from NYC TLC
        external:
          location: '/data/raw'
          file_format: parquet
          pattern: 'yellow_tripdata_*.parquet'

